# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelPlanner
  pod 'Pulley'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'RealmSwift'
  pod 'SFSafeSymbols', '~> 1.0.1'

end
